== La vie d'une JEP
Une JEP va passer par différent état.

*  Draft
*  Posted
*  Submitted
*  Candidate
*  Funded
*  Completed

[.notes]
--
*  Draft (brouillon) :

Permet à l'auteur de la JEP de la faire circuler pour un premier examen, d'en discuter avec la communauté et de la travailler.

*  Posted :

La JEP entre dans les archives (de l'auteur) on va lui attribuer un numéro.
Les numéro des JEP démarre à 100.
Les numéro inferieur sont réservé aux JEP de processus (process JEP) qui modifie le processus de développement   d'OpenJDK

*  Submitted :

La JEP est prête pour l'examen et la discussion par la communauté et les responsables du projet.

*  Candidate :

Acceptée pour l'inclusion dans la roadmap par un OpenJDK Lead

*  Funded :

Jugée par un group ou area lead comme "financé" -> assez de personnes travaille dessus

*  Completed : Fini et livrée.
--

=== états particuliers.

* Withdrawn
*  Rejected
*  Active

[.notes]
--
*  Withdrawn (retiré) :

Retiré par l'auteur. Peut être reformulé ultérieurement.

*  Rejected :

identifiée comme une idée qui ne vaut *pas la peine d'être poursuivie*, ou comme une idée qui a si *peu de chances d'être financée* qu'elle ne vaut pas la peine d'être maintenue dans la feuille de route.

*  Active :

Approuvée pour publication par l'OpenJDK Lead.
Utilisée pour les JEP d'information et du process (JEP 1, 2, 3, 2.0....)
--