name: Build and deploy latest version

on:
  push:
    branches:
      - '*'

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install required dependencies
        run: ./setup.sh

      - name: Install and Build 🔧
        uses: addnab/docker-run-action@v3
        with:
          image: asciidoctor/docker-asciidoctor:1.80.0
          options: -v ${{ github.workspace }}/slides:/documents
          run: asciidoctor-revealjs -r asciidoctor-diagram /documents/index.adoc

          # Étape intermédiaire : Inspecter le contenu du répertoire et des fichiers
      - name: Inspect directory and files
        run: |
          echo "Listing directory contents:"
          ls -la
          echo "Listing directory contents:"
          ls -la slides

      - name: Copy build to folder 📦
        run: |
          cd slides && \
          mkdir -p build/reveal.js/dist && \
          cp -r *.html images css highlight.js build/ && \
          cp -r reveal.js/dist/* build/reveal.js/dist/ && \
          cp -r reveal.js/plugin build/reveal.js/

       # Étape intermédiaire : Inspecter le contenu du répertoire et des fichiers
      - name: Inspect directory and files
        run: |
          echo "Listing directory contents:"
          ls -la
          echo "Listing directory contents:"
          ls -la slides
          echo "Listing directory contents:"
          ls -la slides/build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: slides/build
          branch: gh-pages
#          clean: false